version: '3.8'

services:
  react-frontend:
    container_name: frontend
    restart: unless-stopped
    image: react-frontend
    build:
      context: frontend
      target: production
      dockerfile: Dockerfile
    ports:
      - "80:5050"
    networks:
      - fullstack-network

  product-web-tracker:
    container_name: product-web-tracker
    restart: unless-stopped
    image: product-web-tracker
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    networks:
      - fullstack-network
networks:
  fullstack-network:
    driver: bridge
